---
__tmp_dir:              "{{ tmp_dir | default('/opt/IBM/Binaries') }}/was"
__logs_dir:             "{{ tmp_dir | default('/opt/IBM/Binaries') }}/logs"
__iim_install_location: "{{ iim_install_location  | default('/opt/IBM/InstallationManager') }}"
__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__imshared_location:    "{{ imshared_location  | default('/opt/IBM/IMShared') }}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:             "{{ __logs_dir }}/was_nd.rsp"
__log_file:             "{{ __logs_dir }}/was_nd_install.{{ __now }}.log"
__tpl_file:             "was_nd.rsp.j2"
__was_files:
  - { file_name: was.repo.90501.nd.zip, check_sum: afd5c4f868ba0fd52f348aa292f67595b0552a0e54b31d4d8054ffb546841cf4 }
__this_version:         "{{ was_version | default('9.0.5001.20190828_0616') }}"
__product_id:           "\"id='com.ibm.websphere.ND.v90'\""
__version_check:        "Installed com.ibm.websphere.ND.v90_9.0.5001"
__iim_product_id:       "\"id='com.ibm.cic.agent\""
