---
- name:          Cleanup Java Binaries directory
  file:          path={{ __java_tmp_dir }} state=absent
  ignore_errors: true

- name:          Cleanup IHS Binaries directory
  file:          path={{ __ihs_dir }} state=absent
  ignore_errors: true

- name:          Cleanup WCT Binaries directory
  file:          path={{ __wct_dir }} state=absent
  ignore_errors: true

- name:          Cleanup Plugins Binaries directory
  file:          path={{ __plg_dir }} state=absent
  ignore_errors: true

#-  debug:       var=version_already_installed
- name:          Create Java Binaries directory
  file:          path={{ __java_tmp_dir }} state=directory mode=0755

- name:          Create IHS Binaries directory
  file:          path={{ __ihs_dir }} state=directory mode=0755

- name:          Create WCT Binaries directory
  file:          path={{ __wct_dir }} state=directory mode=0755

- name:          Create Plugins Binaries directory
  file:          path={{ __ihs_dir }} state=directory mode=0755

- name:          Create Logs directory
  file:          path={{ __plg_dir }} state=directory mode=0755
  
- name:          Download WAS Java
  get_url:
    url:         "{{ was_repository_url }}/{{ item.file_name }}"
    dest:        "{{ __java_tmp_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __java_files }}"

- name:          Extract WAS Java
  unarchive:
    src:         "{{ __java_tmp_dir }}/{{ item.file_name }}"
    dest:        "{{ __java_tmp_dir }}/"
    copy:        no
  with_items:    "{{ __java_files }}"

- name:          Download IBM HTTP Server Files
  get_url:
    url:         "{{ __repository_url }}/{{ item.file_name }}"
    dest:        "{{ __ihs_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __ihs_files }}"

- name:          Extract IBM HTTP Server Files
  unarchive:
    src:         "{{ __ihs_dir }}/{{ item.file_name }}"
    dest:        "{{ __ihs_dir }}/"
    copy:        no
  with_items:    "{{ __ihs_files }}"

- name:          Download WCT Files
  get_url:
    url:         "{{ __repository_url }}/{{ item.file_name }}"
    dest:        "{{ __wct_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __wct_files }}"

- name:          Extract WCT Files
  unarchive:
    src:         "{{ __wct_dir }}/{{ item.file_name }}"
    dest:        "{{ __wct_dir }}/"
    copy:        no
  with_items:    "{{ __wct_files }}"

- name:          Download Plugins Files
  get_url:
    url:         "{{ __repository_url }}/{{ item.file_name }}"
    dest:        "{{ __plg_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __plg_files }}"

- name:          Extract Plugins Files
  unarchive:
    src:         "{{ __plg_dir }}/{{ item.file_name }}"
    dest:        "{{ __plg_dir }}/"
    copy:        no
  with_items:    "{{ __plg_files }}"

- name:          Generate Response file
  template:
    src:         "{{ __tpl_file }}"
    dest:        "{{ __rsp_file }}"

- name:          Install IBM HTTP Server Software
  command:
    chdir={{ __ihs_dir }}
    {{ __iim_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ __log_file }} input {{ __rsp_file }}
  register:      cout
  changed_when:  ( cout.stdout.find(__version_check) != -1)

#- debug:        var=cout
- name:          Cleanup Java Binaries directory
  file:          path={{ __java_tmp_dir }} state=absent

- name:          Cleanup IHS Binaries directory
  file:
    state:       absent
    path:        "{{ __ihs_dir }}"
